name: CI

on:
  push:
    paths:
      - 'timeweb/**'
  pull_request:
    paths:
      - 'timeweb/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Flask pytest  

      - name: Create virtual environment
        run: |
          python -m venv venv  
          echo "Virtual environment created"

      - name: Install dependencies in virtual environment
        run: |
          . venv/bin/activate  
          pip install Flask pytest  

      - name: Run Makefile targets
        run: |
          . venv/bin/activate && make test  
        working-directory: ./timeweb
