name: CI

on:
  push:
    paths:
      - 'timeweb/**'
  pull_request:
    paths:
      - 'timeweb/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Flask pytest

      - name: Run Makefile targets
        run: |
          make test
        working-directory: ./timeweb
